name: integration

on: push

jobs:
  checkCodestyle:
    runs-on: ubuntu-latest
    steps:
        run: |
          npm install
          npx eslint .
        env:
          integration: true

